<a href="https://colab.research.google.com/github/robinkm0610/Machine_learning_dump/blob/main/Codebasics_ML_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression Multiple Variables

price(Dependent variable) = m1 * area + m2 * bedrooms + m3* ages + b </br>
m1, m2, m3 = coefficients </br>
area, bedrooms, age are independent variables (features) </br>
while b is the intercept</br>
y = m1x1 + m2x2 + m3x3 + b

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv(r"homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
#data preprocessing
#fill the na values with median
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [11]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [22]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [23]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [24]:
reg.intercept_

221323.00186540396

In [19]:
#predict the price of a home where the area is 3000 sq.ft 3 bedroom, and 15 year old
#predict the price of a home where the area is 2500 sq.ft 4 bedroom, and 5 year old
reg.predict([[3000,3,15]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

In [25]:
y = 112.06244194 * 3000 + 23388.88007794* 3 + -3231.71790863* 15 + 221323.00186540396
y

579201.1992897739

In [26]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

### Practice Excercise

In [28]:
!pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=bc8c10def2a1ee7028c66c5f378442b82165a0f43421d5b1183c5eae842502a8
  Stored in directory: /root/.cache/pip/wheels/a0/4a/5b/d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [29]:
from word2number import w2n

In [31]:
df1 = pd.read_csv(r"hiring.csv")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
#data preprocessing
# replace all the empty cells in experience with zero and convert to numbers(linear model works only with numbers)
# replace all the empty cells in test score with mean


In [36]:
df1.experience = df1.experience.fillna("zero")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [40]:
import math
test_score_mean = math.floor(df1['test_score(out of 10)'].mean())
test_score_mean

7

In [43]:
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(test_score_mean)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [45]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()

In [46]:
# 2 yr exp, 9 test score, 6 interview score

reg1.predict([[2,9,6]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [47]:
# 12 yr exp, 10 test score, 10 interview score
reg1.predict([[12,10,10]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])