<a href="https://colab.research.google.com/github/robinkm0610/Machine_learning_dump/blob/main/Macchine_Learning/Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python


Advantages of Numpy Arrays:
1. Allows serverals Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

Lits vs Numpy - Time Taken

In [5]:
from time import process_time

In [7]:
#TIme taken by a list
lst = [i for i in range(10000)]
srt_time = process_time()
lst =  [i+5 for i in lst]
end_time = process_time()

print(end_time - srt_time)

0.0010463039999999424


In [8]:
np_array = np.array([i for i in range(10000)] )
srt_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - srt_time)

0.0005586590000001834


In [9]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
#Creating a 1 dimentional array
a  = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

In [13]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
b.shape

(2, 4)

In [15]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [16]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
#create an identity matri
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.7538262  0.43132661 0.05627696 0.06451182]
 [0.80435674 0.35389026 0.76940261 0.24823206]
 [0.4946683  0.98057958 0.27998088 0.79361622]]


In [24]:
#random interger values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[96 70 40 57 83]
 [67 34 72 22 23]
 [44 37 72 71 47]]


In [27]:
#array of evenly spaced values ---> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [28]:
#array of evenly spaced values --> specifying the step
e  = np.arange(10,30,5)
print(e)


[10 15 20 25]


In [29]:
#convert an list to an array
list2 = [10,20,30,40]
np_array = np.asarray(list2)
print(list2)
type(np_array)

[10, 20, 30, 40]


numpy.ndarray

In [30]:
#Analysing  a numpy array
c = np.random.randint(10,90,(5,5))
print(c)

[[48 75 73 85 58]
 [49 72 82 39 43]
 [11 54 67 24 18]
 [57 60 81 63 33]
 [49 39 75 28 46]]


In [31]:
#array dimension
print(c.shape)


(5, 5)


In [32]:
#number of dimensions
print(c.ndim)

2


In [33]:
#number of elements in an array
print(c.size)

25


In [35]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations in an np array

In [36]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2) #concatenate or join 2 lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 8 6]
 [1 1 2]
 [3 3 6]]
[[13 11 17]
 [11 12 14]
 [12 12 19]]


In [38]:
print(a+b)

[[20 19 23]
 [12 13 16]
 [15 15 25]]


In [39]:
print(b-a)

[[ 6  3 11]
 [10 11 12]
 [ 9  9 13]]


In [40]:
print(a*b)

[[ 91  88 102]
 [ 11  12  28]
 [ 36  36 114]]


In [41]:
print(b/a)

[[ 1.85714286  1.375       2.83333333]
 [11.         12.          7.        ]
 [ 4.          4.          3.16666667]]


In [42]:
print(np.add(a,b))

[[20 19 23]
 [12 13 16]
 [15 15 25]]


In [43]:
print(np.subtract(a,b))

[[ -6  -3 -11]
 [-10 -11 -12]
 [ -9  -9 -13]]


In [44]:
print(np.multiply(a,b))

[[ 91  88 102]
 [ 11  12  28]
 [ 36  36 114]]


In [45]:
print(np.divide(a,b))

[[0.53846154 0.72727273 0.35294118]
 [0.09090909 0.08333333 0.14285714]
 [0.25       0.25       0.31578947]]


Array Manipulation

In [46]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 4 3]
 [0 0 3]]
(2, 3)


In [47]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 0]
 [4 0]
 [3 3]]
(3, 2)


In [48]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 3 7]
 [1 2 2]]
(2, 3)


In [50]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 1]
 [3 2]
 [7 2]]
(3, 2)


In [53]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[7 1 4]
 [6 1 6]]
(2, 3)


In [54]:
b = a.reshape(3,2)
print(b)
print(b.shape)


[[7 1]
 [4 6]
 [1 6]]
(3, 2)
